# Generated by Django 4.2.17 on 2025-03-17 06:58

from django.db import migrations

def insert_currencies(apps, schema_editor):
    currency_model = apps.get_model('common', 'Currency')
    initial_data = [
        {
            'iso_code': 'USD',
            'name': 'United States Dollar',
            'symbol': '$',
        },
        {
            'iso_code': 'EUR',
            'name': 'Euro',
            'symbol': '€',
        },
        {
            'iso_code': 'GBP',
            'name': 'British Pound Sterling',
            'symbol': '£',
        },
        {
            'iso_code': 'JPY',
            'name': 'Japanese Yen',
            'symbol': '¥',
        },
        {
            'iso_code': 'CNY',
            'name': 'Chinese Yuan Renminbi',
            'symbol': '¥',
        },

    ]
    for data in initial_data:
        currency_model.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_currencies),
    ]
