# Generated by Django 4.2.17 on 2025-03-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20250317_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('currency', 'Currency')], max_length=20, unique=True)),
                ('value', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
