# Generated by Django 4.2.17 on 2025-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('filters', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
