# Generated by Django 4.2.17 on 2025-04-07 05:03

from django.db import migrations, models

def create_default_value(apps, schema_editor):
    settings = apps.get_model('common', 'Settings')
    settings.objects.create(type='enable_template_creation_time', value=1)

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_filterset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='type',
            field=models.CharField(choices=[('currency', 'Currency'), ('enable_template_creation_time', 'Enable template creation time')], max_length=50, unique=True),
        ),
        migrations.RunPython(create_default_value),
    ]
