# Generated by Django 4.2.17 on 2025-08-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aap_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtuserrefreshtoken',
            name='access_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='aap_auth.jwtusertoken'),
        ),
        migrations.AlterField(
            model_name='jwtuserrefreshtoken',
            name='token',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jwtusertoken',
            name='token',
            field=models.TextField(db_index=True),
        ),
    ]
