---
- name: Create the postgresql admin password secret
  containers.podman.podman_secret:
    name: postgresql_admin_password
    data: '{{ postgresql_admin_password }}'
    force: '{{ postgresql_update_secret | bool }}'
    skip_existing: '{{ not postgresql_update_secret | bool }}'
...
