---
- name: Ensure reporter admin password is provided
  ansible.builtin.assert:
    that:
      - reporter_admin_password is defined
      - reporter_admin_password | length
    fail_msg: 'reporter_admin_password must be set and not empty'

- name: Ensure reporter postgresql host and password are provided
  ansible.builtin.assert:
    that:
      - reporter_pg_host is defined
      - reporter_pg_host | length
      - reporter_pg_password is defined
      - reporter_pg_password | length
    fail_msg: 'reporter_pg_host and reporter_pg_password must be set and not empty'
...
