# Generated by Django 4.2.17 on 2025-01-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('access_token', models.TextField()),
                ('verify_ssl', models.BooleanField(default=True)),
            ],
        ),
    ]
