# Generated by Django 4.2.17 on 2025-02-04 13:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('access_token', models.TextField()),
                ('verify_ssl', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutionEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('is_container_group', models.BooleanField(default=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField()),
                ('type', models.CharField(choices=[('job', 'Job'), ('Playbook Run', 'Playbook Run')], default='job', max_length=20)),
                ('job_type', models.CharField(choices=[('run', 'Run'), ('check', 'Check'), ('scan', 'Scan')], default='job', max_length=20)),
                ('launch_type', models.CharField(choices=[('manual', 'Manual'), ('relaunch', 'Relaunch'), ('callback', 'Callback'), ('scheduled', 'Scheduled'), ('dependency', 'Dependency'), ('workflow', 'Workflow'), ('webhook', 'Webhook'), ('sync', 'Sync'), ('scm', 'SCM Update')], default='manual', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('waiting', 'Waiting'), ('running', 'Running'), ('successful', 'Successful'), ('failed', 'Failed'), ('error', 'Error'), ('canceled', 'Canceled')], default='successful', max_length=25)),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('elapsed', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15)),
                ('failed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('num_hosts', models.IntegerField(default=0)),
                ('changed_hosts_count', models.IntegerField(default=0)),
                ('dark_hosts_count', models.IntegerField(default=0)),
                ('failures_hosts_count', models.IntegerField(default=0)),
                ('ok_hosts_count', models.IntegerField(default=0)),
                ('processed_hosts_count', models.IntegerField(default=0)),
                ('skipped_hosts_count', models.IntegerField(default=0)),
                ('failed_hosts_count', models.IntegerField(default=0)),
                ('ignored_hosts_count', models.IntegerField(default=0)),
                ('rescued_hosts_count', models.IntegerField(default=0)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
                ('execution_environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clusters.executionenvironment')),
                ('instance_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clusters.instancegroup')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clusters.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
            options={
                'abstract': False,
                'index_together': {('cluster', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('manual_time_minutes', models.IntegerField(default=60)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='clusters.job')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clusters.label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobHostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('host_name', models.CharField(max_length=255)),
                ('changed', models.IntegerField(default=0)),
                ('dark', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('failed', models.BooleanField(default=False)),
                ('ignored', models.IntegerField(default=0)),
                ('rescued', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clusters.host')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_summary', to='clusters.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clusters.jobtemplate'),
        ),
        migrations.AddField(
            model_name='job',
            name='launched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clusters.aapuser'),
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clusters.organization'),
        ),
        migrations.CreateModel(
            name='ClusterSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('last_job_finished_date', models.DateTimeField()),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='clusters.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterSyncData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_created', models.DateTimeField(auto_now_add=True)),
                ('internal_modified', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_data', to='clusters.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aapuser',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(django.db.models.functions.datetime.TruncDate('finished'), models.F('finished'), name='finished_date_idx'),
        ),
        migrations.AlterIndexTogether(
            name='job',
            index_together={('cluster', 'job_template')},
        ),
        migrations.AlterIndexTogether(
            name='instancegroup',
            index_together={('cluster', 'external_id')},
        ),
        migrations.AlterIndexTogether(
            name='aapuser',
            index_together={('cluster', 'external_id')},
        ),
    ]
