# Generated by Django 4.2.17 on 2025-01-28 11:38

from django.db import migrations
from django.db.backends.postgresql.psycopg_any import mogrify


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instance',
            new_name='Cluster',
        ),
    ]
