# Generated by Django 4.2.17 on 2025-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='finished_date_idx',
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='manual_time_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'finished'], name='clusters_jo_status_1b529e_idx'),
        ),
    ]
