# Generated by Django 4.2.17 on 2025-02-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_project_job_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhostsummary',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clusters.host'),
        ),
        migrations.AlterField(
            model_name='jobhostsummary',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
