# Generated by Django 4.2.17 on 2025-03-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_alter_jobhostsummary_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='manual_time_minutes',
            new_name='time_taken_manually_execute_minutes',
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='time_taken_create_automation_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
