# Generated by Django 4.2.17 on 2025-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0005_rename_manual_time_minutes_jobtemplate_time_taken_manually_execute_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
