# Generated by Django 4.2.17 on 2025-03-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0006_alter_cluster_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='time_taken_manually_execute_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
