# Generated by Django 4.2.17 on 2025-04-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0007_alter_jobtemplate_time_taken_manually_execute_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='time_taken_manually_execute_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
