# Generated by Django 4.2.17 on 2025-04-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0008_alter_jobtemplate_time_taken_manually_execute_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to='clusters.organization'),
        ),
    ]
