# Generated by Django 4.2.17 on 2025-05-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0009_jobtemplate_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='aap_version',
            field=models.CharField(choices=[('AAP 2.5', 'AAP 2.5'), ('AAP 2.4', 'AAP 2.4')], default='AAP 2.4', max_length=15),
        ),
    ]
