# Generated by Django 4.2.17 on 2025-08-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0010_cluster_aap_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='time_taken_manually_execute_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
