# Generated by Django 4.2.17 on 2025-08-18 06:12

from django.db import migrations, models

def copy_value(apps, schema_editor):
    clusters = apps.get_model('clusters', 'Cluster')
    for cluster in clusters.objects.all():
        cluster.access_token_str = cluster.access_token
        cluster.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0011_alter_jobtemplate_time_taken_manually_execute_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='access_token_str',
            field=models.TextField(blank=True, null=True, default=''),
        ),
        migrations.RunPython(copy_value),
    ]
