# Generated by Django 4.2.17 on 2025-08-18 06:22

from django.db import migrations, models
from backend.apps.clusters.encryption import encrypt_value

def encrypt_token(apps, schema_editor):
    clusters = apps.get_model('clusters', 'Cluster')

    for cluster in clusters.objects.all():
        cluster.access_token = encrypt_value(cluster.access_token_str)
        cluster.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0012_cluster_access_token_str'),
    ]

    operations = [
        migrations.RunPython(encrypt_token),
        migrations.RemoveField(
            model_name='cluster',
            name='access_token_str',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='access_token',
            field=models.BinaryField(),
        ),
    ]
