# Generated by Django 4.2.17 on 2025-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0013_remove_cluster_access_token_str_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtemplate",
            name="time_taken_manually_execute_minutes",
            field=models.IntegerField(default=1),
        ),
    ]
