# Generated by Django 4.2.17 on 2025-09-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0014_alter_jobtemplate_time_taken_manually_execute_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="client_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="cluster",
            name="client_secret",
            field=models.BinaryField(
                default=b"gAAAAABowrlA3VGeQTqam2njNmOG4-J9vo1m0tSE3ClWGz49VADhsjHwHIAObp3xTOexkp5KyY5r6XyxWG8x3JooZ063Cw12BA=="
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="refresh_token",
            field=models.BinaryField(
                default=b"gAAAAABowrlA3VGeQTqam2njNmOG4-J9vo1m0tSE3ClWGz49VADhsjHwHIAObp3xTOexkp5KyY5r6XyxWG8x3JooZ063Cw12BA=="
            ),
        ),
    ]
