# Generated by Django 4.2.17 on 2025-10-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0015_cluster_client_id_cluster_client_secret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="aap_version",
            field=models.CharField(
                choices=[
                    ("AAP 2.6", "AAP 2.6"),
                    ("AAP 2.5", "AAP 2.5"),
                    ("AAP 2.4", "AAP 2.4"),
                ],
                default="AAP 2.4",
                max_length=15,
            ),
        ),
    ]
