# Generated by Django 4.2.17 on 2025-10-21 06:04

from django.db import migrations, transaction
from django.db.models import Min


def unique_negative_external_ids(apps, schema_editor):
    models = [
        {
            "app_model": apps.get_model('clusters', 'Organization'),
        },
        {
            "app_model": apps.get_model('clusters', 'JobTemplate'),
        },
        {
            "app_model": apps.get_model('clusters', 'AAPUser'),
        },
        {
            "app_model": apps.get_model('clusters', 'Inventory'),
        },
        {
            "app_model": apps.get_model('clusters', 'ExecutionEnvironment'),
        },
        {
            "app_model": apps.get_model('clusters', 'InstanceGroup'),
        },
        {
            "app_model": apps.get_model('clusters', 'Project'),
        },
        {
            "app_model": apps.get_model('clusters', 'Label'),
        },
        {
            "app_model": apps.get_model('clusters', 'Host'),
        },
    ]
    with transaction.atomic():
        for model in models:
            app_model = model['app_model']
            negative_ids = app_model.objects.filter(external_id__lt=0).order_by('internal_created')
            _min = app_model.objects.all().aggregate(Min('external_id'))
            min_id = _min['external_id__min'] if _min['external_id__min'] is not None else 0
            for index, obj in enumerate(negative_ids):
                min_id = min_id - 1
                obj.external_id = min_id
                obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('clusters', '0015_auto_20251020_1008'),
    ]

    operations = [
        migrations.RunPython(unique_negative_external_ids),
        migrations.AlterIndexTogether(
            name='aapuser',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='instancegroup',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='label',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='aapuser',
            unique_together={('cluster', 'name', 'type'), ('cluster', 'external_id', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='executionenvironment',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='instancegroup',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtemplate',
            unique_together={('cluster', 'external_id', 'organization'), ('cluster', 'name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
    ]
