# Generated by Django 4.2.17 on 2025-10-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0015_auto_20251020_1008'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='aapuser',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='instancegroup',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='label',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='aapuser',
            unique_together={('cluster', 'name', 'type'), ('cluster', 'external_id', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='executionenvironment',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='instancegroup',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtemplate',
            unique_together={('cluster', 'external_id', 'organization'), ('cluster', 'name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('cluster', 'name'), ('cluster', 'external_id')},
        ),
    ]
