# Generated by Django 4.2.17 on 2025-10-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0016_alter_aapuser_index_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
