# Generated by Django 4.2.17 on 2025-10-28 04:23
import decimal
from decimal import Decimal
import django.core.validators
from django.db import migrations, models

def update_templates(apps, schema_editor):
    max_value = 1000000
    min_value = 1

    jobs_template_model = apps.get_model('clusters', 'JobTemplate')

    templates = jobs_template_model.objects.filter(
        models.Q(time_taken_manually_execute_minutes__gt=max_value) |
        models.Q(time_taken_manually_execute_minutes__lt=min_value) |
        models.Q(time_taken_create_automation_minutes__gt=max_value) |
        models.Q(time_taken_create_automation_minutes__lt=min_value)
    )
    for template in list(templates):
        if template.time_taken_manually_execute_minutes > max_value:
            template.time_taken_manually_execute_minutes = max_value
        elif template.time_taken_manually_execute_minutes < min_value:
            template.time_taken_manually_execute_minutes = min_value

        if template.time_taken_create_automation_minutes > max_value:
            template.time_taken_create_automation_minutes = max_value
        elif template.time_taken_create_automation_minutes < min_value:
            template.time_taken_create_automation_minutes = min_value
        template.save()

def update_costs(apps, schema_editor):
    max_value = decimal.Decimal(1000)
    cost_model = apps.get_model('clusters', 'Costs')

    costs = cost_model.objects.filter(value__gt=max_value)
    for c in costs:
        c.value = max_value
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0017_alter_job_started'),
    ]

    operations = [
        migrations.RunPython(update_templates),
        migrations.RunPython(update_costs),
        migrations.AlterField(
            model_name='costs',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))]),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='time_taken_create_automation_minutes',
            field=models.BigIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='time_taken_manually_execute_minutes',
            field=models.BigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
