# Generated by Django 5.2.8 on 2025-11-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0018_alter_costs_value_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='clusters_jo_cluster_54f471_idx',
            old_fields=('cluster', 'job_template'),
        ),
    ]
