# Generated by Django 4.2.17 on 2025-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0018_alter_costs_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="client_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="cluster",
            name="client_secret",
            field=models.BinaryField(default=b""),
        ),
        migrations.AddField(
            model_name="cluster",
            name="refresh_token",
            field=models.BinaryField(default=b""),
        ),
    ]
