# Generated by Django 5.2.8 on 2025-11-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0020_alter_cluster_aap_version"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="job",
            new_name="clusters_jo_cluster_54f471_idx",
            old_fields=("cluster", "job_template"),
        ),
    ]
