# Generated by Django 5.2.8 on 2025-12-11 14:48
from django.db import migrations

def update_values(apps, schema_editor):
    costs = apps.get_model('clusters', 'Costs')
    for cost in costs.objects.filter(type='manual'):
        value = cost.value
        cost.value = value * 60  # Convert cost per minute to cost per hour
        cost.save()

class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0021_rename_job_cluster_job_template_clusters_jo_cluster_54f471_idx"),
    ]

    operations = [
        migrations.RunPython(update_values),
    ]
