# Generated by Django 5.2.8 on 2026-03-03 05:06

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def update_values(apps, schema_editor):
    costs = apps.get_model('clusters', 'Costs')
    if not costs.objects.exists():
        # No legacy data to migrate; leave SubscriptionCost empty so SubscriptionCost.get()
        # can seed defaults at runtime.
        return
    monthly_subscription_costs = Decimal('0.01')
    engineer_avg_hourly_rate = Decimal('0.01')
    for cost in costs.objects.all():
        if cost.type == 'automated':
            # Convert cost per minute to monthly subscription cost (assuming 30 days in a month)
            monthly_subscription_costs = cost.value * 60 * 24 * 30
        elif cost.type == 'manual':
            engineer_avg_hourly_rate = cost.value
    subscription_cost = apps.get_model('clusters', 'SubscriptionCost')
    subscription_cost.objects.update_or_create(
        pk=1,
        defaults={
            "monthly_subscription_cost": monthly_subscription_costs,
            "engineer_avg_hourly_rate": engineer_avg_hourly_rate,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ('clusters', '0022_manual_cost_to_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_subscription_cost', models.DecimalField(decimal_places=2, default=Decimal('0.01'),
                                                                  help_text='Monthly subscription cost for AAP subscription',
                                                                  max_digits=15, validators=[
                        django.core.validators.MinValueValidator(Decimal('0.01')),
                        django.core.validators.MaxValueValidator(Decimal('1000000'))])),
                ('engineer_avg_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.01'),
                                                                 help_text='Average hourly rate for engineers performing manual tasks (used for cost calculations in reports)',
                                                                 max_digits=15, validators=[
                        django.core.validators.MinValueValidator(Decimal('0.01')),
                        django.core.validators.MaxValueValidator(Decimal('1000'))])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(update_values, migrations.RunPython.noop),
    ]
