# Generated by Django 5.2.8 on 2026-05-26 14:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0025_add_aap_27_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncost',
            name='monthly_subscription_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Monthly cost of running the Ansible Automation Platform. This value includes license, labor and infrastructure costs to run AAP. It is used to calculate the automation savings.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1000000'))]),
        ),
    ]
