---
- name: Preflight checks
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Get ostree fact
      ansible.builtin.import_role:
        name: common
        tasks_from: ostree.yml

    - name: Run preflight checks
      ansible.builtin.import_role:
        name: preflight

- name: Install common container components
  hosts: automationcontroller:automationeda:automationhub:database:execution_nodes:automationreporter
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
      become: true

    - name: Gather regular user id, uid and home dir
      ansible.builtin.setup:
        filter:
          - 'ansible_user_id'
          - 'ansible_user_uid'
          - 'ansible_user_dir'

    - name: Install and configure podman
      ansible.builtin.import_role:
        name: common

- name: Install the database
  hosts: database
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Install and configure postgresql
      ansible.builtin.import_role:
        name: postgresql

- name: Install the Automation Reporter
  any_errors_fatal: true
  hosts: automationreporter
  gather_facts: false
  become: false
  tasks:
    - name: Install and configuration automation reporter
      ansible.builtin.import_role:
        name: automationreporter
...
