---
- name: Collect services facts
  hosts: automationcontroller:automationeda:automationhub:database:execution_nodes
  gather_facts: false
  become: false
  tasks:
    - name: Gather regular user uid and home dir
      ansible.builtin.setup:
        filter:
          - 'ansible_user_uid'
          - 'ansible_user_dir'

    - name: Get service facts
      ansible.builtin.service_facts:
      become: true

- name: Uninstall the Automation Controller
  hosts: automationcontroller
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall the automation controller
      ansible.builtin.import_role:
        name: automationcontroller
        tasks_from: uninstall.yml

- name: Uninstall the Automation Hub
  hosts: automationhub
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall the automation hub
      ansible.builtin.import_role:
        name: automationhub
        tasks_from: uninstall.yml

- name: Uninstall the Automation EDA
  hosts: automationeda
  gather_facts: false
  tasks:
    - name: Uninstall the automation eda
      ansible.builtin.import_role:
        name: automationeda
        tasks_from: uninstall.yml

- name: Uninstall receptor
  hosts: automationcontroller:execution_nodes
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall receptor
      ansible.builtin.import_role:
        name: receptor
        tasks_from: uninstall.yml

- name: Uninstall redis
  hosts: automationcontroller:automationeda:automationhub
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall redis
      ansible.builtin.import_role:
        name: redis
        tasks_from: uninstall.yml

- name: Uninstall the database
  hosts: database
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall postgresql
      ansible.builtin.import_role:
        name: postgresql
        tasks_from: uninstall.yml

- name: Remove service leftovers
  hosts: automationcontroller:automationeda:automationhub
  gather_facts: false
  become: false
  tasks:
    - name: Run ostree tasks
      ansible.builtin.import_role:
        name: common
        tasks_from: ostree.yml

    - name: Remove python packages used by collections
      ansible.builtin.package:
        name:
          - python3-psycopg2
        state: absent
      become: true
      when: not ostree | bool

- name: Uninstall common container components
  hosts: automationcontroller:automationeda:automationhub:database:execution_nodes
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall podman
      ansible.builtin.import_role:
        name: common
        tasks_from: uninstall.yml
...
