apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/ansible-automation-platform/automation-reports?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "release-0.4"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: automation-reports
    appstudio.openshift.io/component: automation-reports
    pipelines.appstudio.openshift.io/type: build
  name: automation-reports-on-pull-request
  namespace: es-team-tenant
spec:
  timeouts:
    pipeline: "8h0m0s"
    tasks: "4h0m0s"
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/es-team-tenant/automation-reports:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/arm64
    - name: dockerfile
      value: docker/Dockerfile.backend
    - name: path-context
      value: .
    - name: submodules
      value: "false"
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: '[{"type": "npm", "path": "."}, {"type": "rpm", "path": "."}, {"type": "pip", "path": ".", "requirements_files": ["requirements-build.txt"], "requirements_build_files": ["requirements-build-tools.txt"]}]'
    - name: build-source-image
      value: "true"
    #- name: skip-checks
    #  value: "true"
    - name: log-level
      value: info
    - name: enable-cache-proxy
      value: "true"
  pipelineRef:
    resolver: bundles
    params:
      - name: name
        value: pde-docker-build-multiplatform-submodules-env-oci-ta
      - name: bundle
        value: quay.io/aap-ci/pde-docker-build-multiplatform-submodules-env-oci-ta-bundle@sha256:f9fdc9370fa431a3f930642c8bee4c4750b04be747a4d17136d62476aa35e6bc
      - name: kind
        value: pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-automation-reports
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
