---
- name: Get sysctl net.ipv4.ip_unprivileged_port_start setting
  ansible.builtin.slurp:
    src: /proc/sys/net/ipv4/ip_unprivileged_port_start
  register: _sysctl_cmd

- name: Allow rootless container to bind from port 80 onwards
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '{{ _reporter_ports | union(_sysctl_unprivileged_port_start) | min }}'
    sysctl_set: true
    state: present
    reload: true
  become: true
  vars:
    _sysctl_unprivileged_port_start: "[{{ _sysctl_cmd['content'] | b64decode }}]"
  when: (_reporter_ports | min) < 1024

- name: Create the nginx directory
  ansible.builtin.file:
    path: '{{ nginx_conf_dir }}'
    mode: '0770'
    state: directory

- name: Create the nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: '{{ nginx_conf_dir }}/reporter.conf'
    mode: '0640'
  notify: Restart reporter web

- name: TEMP HACK Install htpasswd utility
  ansible.builtin.package:
    name: httpd-tools
    state: present
  become: true
  when: nginx_hack_enable_basic_auth | bool

- name: TEMP HACK Create the nginx htpasswd file
  ansible.builtin.command:
    cmd: htpasswd -bc '{{ nginx_conf_dir }}/htpasswd' '{{ nginx_hack_basic_auth_username }}' '{{ nginx_hack_basic_auth_password }}'
  when: nginx_hack_enable_basic_auth | bool
  notify: Restart reporter web

- name: TEMP HACK Remove the nginx htpasswd file
  ansible.builtin.file:
    path: '{{ nginx_conf_dir }}/htpasswd'
    state: absent
  when: not nginx_hack_enable_basic_auth | bool
  notify: Restart reporter web
...
