---
- name: Create the dashboard postgres secret
  containers.podman.podman_secret:
    name: dashboard_postgres
    data: '{{ lookup("ansible.builtin.template", "postgres.py.j2") }}'
    force: '{{ dashboard_update_secret | bool }}'
    skip_existing: '{{ not dashboard_update_secret | bool }}'
  notify:
    # - Restart dashboard rsyslog
    - Restart dashboard task
    - Restart dashboard web

- name: Create the dashboard SECRET_KEY secret
  containers.podman.podman_secret:
    name: dashboard_secret_key
    data: '{{ dashboard_secret_key | default(lookup("ansible.builtin.password", "/dev/null length=50")) }}'
    force: '{{ dashboard_update_secret | bool }}'
    skip_existing: '{{ not dashboard_update_secret | bool }}'
  notify:
    # - Restart dashboard rsyslog
    - Restart dashboard task
    - Restart dashboard web
...
