---
- name: Create the reporter postgres secret
  containers.podman.podman_secret:
    name: reporter_postgres
    data: '{{ lookup("ansible.builtin.template", "postgres.py.j2") }}'
    force: '{{ reporter_update_secret | bool }}'
    skip_existing: '{{ not reporter_update_secret | bool }}'
  notify:
    # - Restart reporter rsyslog
    - Restart reporter task
    - Restart reporter web

- name: Create the reporter SECRET_KEY secret
  containers.podman.podman_secret:
    name: reporter_secret_key
    data: '{{ reporter_secret_key | default(lookup("ansible.builtin.password", "/dev/null length=50")) }}'
    force: '{{ reporter_update_secret | bool }}'
    skip_existing: '{{ not reporter_update_secret | bool }}'
  notify:
    # - Restart reporter rsyslog
    - Restart reporter task
    - Restart reporter web
...
