---
- name: Generate TLS certificate and key
  when:
    - reporter_tls_cert is not defined
    - reporter_tls_key is not defined
  block:
    - name: Install python-cryptography
      ansible.builtin.package:
        name: python3-cryptography
      become: true
      when: not ostree | bool

    - name: Check the current reporter private key
      ansible.builtin.stat:
        path: '{{ reporter_conf_dir }}/reporter.key'
      register: _reporter_tls_key

    - name: Generate a private key
      community.crypto.openssl_privatekey:
        path: '{{ reporter_conf_dir }}/reporter.key'
        mode: '0400'
      when: not _reporter_tls_key.stat.exists | bool

    - name: Check the current reporter certificate
      ansible.builtin.stat:
        path: '{{ reporter_conf_dir }}/reporter.cert'
      register: _reporter_tls_cert

    - name: Create the reporter TLS certificate
      when: not _reporter_tls_cert.stat.exists | bool
      block:
        - name: Generate a certificate signing request
          community.crypto.openssl_csr_pipe:
            common_name: '{{ _reporter_hostname }}'
            country_name: 'US'
            locality_name: 'Raleigh'
            organization_name: 'Red Hat'
            organizational_unit_name: 'Ansible'
            state_or_province_name: 'North Carolina'
            subject_alt_name: '{{ ["DNS:" + _reporter_hostname] + _reporter_ips }}'
            privatekey_path: '{{ reporter_conf_dir }}/reporter.key'
          register: _reporter_tls_csr

        - name: Generate a self signed x509 certificate
          community.crypto.x509_certificate:
            path: '{{ reporter_conf_dir }}/reporter.cert'
            csr_content: '{{ _reporter_tls_csr.csr }}'
            privatekey_path: '{{ reporter_conf_dir }}/reporter.key'
            provider: ownca
            ownca_path: '{{ _ca_tls_dir }}/ca.cert'
            ownca_privatekey_path: '{{ _ca_tls_dir }}/ca.key'
            mode: '0640'

- name: Import TLS certificate and key
  when:
    - reporter_tls_cert is defined
    - reporter_tls_key is defined
  block:
    - name: Copy reporter TLS certificate
      ansible.builtin.copy:
        src: '{{ reporter_tls_cert }}'
        dest: '{{ reporter_conf_dir }}/reporter.cert'
        mode: '0640'
        remote_src: '{{ reporter_tls_remote | default(false) }}'
      notify: Restart reporter web

    - name: Copy reporter TLS key
      ansible.builtin.copy:
        src: '{{ reporter_tls_key }}'
        dest: '{{ reporter_conf_dir }}/reporter.key'
        mode: '0400'
        remote_src: '{{ reporter_tls_remote | default(false) }}'
      notify: Restart reporter web
...
