---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.16.2
  - name: community.postgresql
    version: 3.3.0
  - name: containers.podman
    version: 1.11.0
#  - name: infra.ah_configuration
#    version: 2.0.4
#  - name: infra.controller_configuration
#    version: 2.6.0
# ansible.controller
