name: "Sync Requirements Files"

on:
    push:
        branches: [main]
        paths:
            - "requirements.txt"
    pull_request:
        paths:
            - "requirements.txt"

jobs:
    sync-requirements:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout automation-reports (${{ github.ref }})"
              uses: actions/checkout@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: "Install pip-tools"
              run: |
                  python -m pip install --upgrade pip
                  pip install pip-tools

            - name: "Sync requirements files"
              run: |
                  chmod +x sync-requirements.sh
                  ./sync-requirements.sh

            - name: "Check for changes"
              id: changes
              run: |
                  if ! git diff --quiet requirements-pinned.txt requirements-build.txt; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                    echo "Requirements files have been updated"
                  else
                    echo "changed=false" >> $GITHUB_OUTPUT
                    echo "Requirements files are up to date"
                  fi

            - name: "Commit and push changes"
              if: steps.changes.outputs.changed == 'true' && github.event_name == 'push'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add requirements-pinned.txt requirements-build.txt
                  git commit -m "Auto-sync requirements files from requirements.txt"
                  git push

            - name: "Add PR comment for changes"
              if: steps.changes.outputs.changed == 'true' && github.event_name == 'pull_request'
              uses: actions/github-script@v7
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '**Requirements files need to be updated**\n\nThe `requirements.txt` file has changed but the requirements files are not in sync. Please run `./sync-requirements.sh` locally and commit the updated requirements files.'
                      })

            - name: "Fail if requirements out of sync in PR"
              if: steps.changes.outputs.changed == 'true' && github.event_name == 'pull_request'
              run: |
                  echo "Requirements files are out of sync. Please run ./sync-requirements.sh locally and commit the changes."
                  git diff requirements-pinned.txt requirements-build.txt
                  exit 1
