name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15  # or any version you need
        env:
          POSTGRES_USER: rootuser
          POSTGRES_PASSWORD: rootpass
          POSTGRES_DB: maindb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U rootuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgres://testuser:testpass@localhost:5432/aapdashboard
    steps:
      - name: Setup DB
        run: |
          until pg_isready -h localhost -p 5432 -U rootuser; do sleep 1; echo "Waiting on DB..."; done
          PGPASSWORD=rootpass psql -h localhost -U rootuser -d postgres -c "CREATE USER testuser WITH PASSWORD 'testpass' CREATEDB;"
        
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Show python version
        run: |
          python3 --version
          pip --version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup .env file
        run: |
          cd src/backend
          cat <<EOF >django_config/local_settings.py
          DB_NAME = "aapdashboard"
          DB_USER = "testuser"
          DB_PASSWORD = "testpass"
          DB_HOST = "localhost"
          DB_PORT = 5432
          EOF
      - name: Run tests
        run: |
          cd src/backend
          export PYTHONPATH=$PWD/..
          pytest --cov=backend --cov-report=term-missing:skip-covered --cov-report=xml:coverage.xml
      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: src/backend/coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            sourceDir: src/backend
